language: csharp
solution: MyStromRestApiCSharp.sln
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ls
  - mono nuget.exe restore MyStromRestApiCSharp.sln -Verbosity Detailed -NonInteractive
  