language: csharp
solution: $SOLUTION_NAME.sln
git:
  depth: false
install:
  - nuget restore $SOLUTION_NAME.sln
before_script:
  - export PATH=$PATH:/home/travis/.dotnet/tools
script:
  - chmod +x ./travis/*
  - ./travis/inst_netcoresdk.sh
  - ./travis/inst_minver.sh
  - source travis/set_minver_version.sh
  - msbuild /p:Configuration=Release /p:VersionNumber=$VERSION $SOLUTION_NAME.sln
deploy:
  skip_cleanup: true
  provider: script
  script: 
    - ./travis/deploy.sh "$NUGET_API_KEY" "Release" "$PROJECT_FILENAME" "$PROJECT_PATH" "$VERSION"
  on:
    branch: master