language: csharp
solution: $SOLUTION_NAME.sln
git:
  depth: false
install:
  - nuget restore $SOLUTION_NAME.sln
script:
  - msbuild /p:Configuration=Release $SOLUTION_NAME.sln
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
  on:
    branch: master