language: csharp
solution: $SOLUTION_NAME.sln
git:
  depth: false
install:
  - nuget restore $SOLUTION_NAME.sln
before_script:
  - export PATH=$PATH:/home/travis/.dotnet/tools
script:
  - sudo apt-get install aspnetcore-runtime-3.1
  - dotnet tool install --global minver-cli --version 2.0.0
  - export VERSION=$(minver)
  - echo $VERSION
  - msbuild /p:Configuration=Release /p:VersionNumber=$VERSION $SOLUTION_NAME.sln
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $SOLUTION_NAME $VERSION
  on:
    branch: master